import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body>
        <header className="fixed top-0 left-0 w-full bg-gray-900 text-white shadow-md z-50">
          <div className="container mx-auto flex justify-between items-center p-4">
            <h1 className="text-xl font-bold">MMA Club</h1>
            <nav>
              <Link href="/" className="hover:text-blue-400 transition-colors">Accueil</Link>
            </nav>
          </div>
        </header>

        <div className="h-20"></div> {/* pour compenser la barre */}

        {children}
      </body>
    </html>
  );
}